version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "KokosnussDEV"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "KokosnussDEV"
    open-pull-requests-limit: 5
    target-branch: "dev"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "KokosnussDEV"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "KokosnussDEV"
    target-branch: "dev"
