version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "kdev"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "kdev"
    open-pull-requests-limit: 5
    target-branch: "dev"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "kdev"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "kdev"
    target-branch: "dev"

    - package-ecosystem: 'docker'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: '⬆️ docker'
          include: 'scope'
      reviewers:
          - 'kdev'
