name: Docker Publish

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Configs
              uses: actions/checkout@v2.3.4
            - name: Build image
              run: docker build . --file Dockerfile --tag add-project-on-labeled
            - name: Log into registry
              run: echo "${{ secrets.DOCKER_ACCESSTOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            - name: Push image
              run: |
                  IMAGE_ID=LEDBrain/add-project-on-labeled
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
                  VERSION=latest
                  echo IMAGE_ID=$IMAGE_ID
                  echo VERSION=$VERSION
                  docker tag add-project-on-labeled $IMAGE_ID:$VERSION
                  docker push $IMAGE_ID:$VERSION